<div id="container-footer">
  <div id="footer">
   
<div id="ipanema">
       <div id="title-footer">A Ipanema</div>
           <ul class="menu3">
            <li><a href="<?php echo $this->baseUrl('/conheca'); ?>" title="Conheça a Ipanema">Conheça a Ipanema</a></li>
            <li><a href="<?php echo $this->baseUrl('/estrutura'); ?>" title="Estrutura">Estrutura</a></li>
            <li><a href="<?php echo $this->baseUrl('/comoingressar'); ?>" title="Como Ingressar">Como Ingressar</a></li>
            <li><a href="<?php echo $this->baseUrl('/noticias'); ?>" title="Notícias">Notícias</a></li>
           </ul>
    </div>
   
    <div id="grad">
       <div id="title-footer">Gradua&ccedil;&atilde;o</div>
      <ul class="menu3">
      		<?php 
      			foreach($this->graduationCourses as $course) : 
      			if(strlen($course->name) > 40)
      			{
      				$courseName = substr($course->name, 0, 37) . '...';
      			} else
      			{
      				$courseName = $course->name;
      			}
      		?>
      		<li><a href="<?php echo $this->baseUrl('/graduacao/' . $course->idgraduation . ',,' . urlencode($course->name)); ?>" title="<?php echo $course->name; ?>"><?php echo $courseName; ?></a></li>
      		<?php 
      			endforeach; 
      		?>
	  </ul>
      
       <div id="title-footer">Idiomas e Extensão</div>
           <ul class="menu3">
            <li><a href="<?php echo $this->baseUrl('/curso/idiomas'); ?>" title="Speak Centro de Idiomas">Speak Centro de Idiomas</a></li>
            <li><a href="<?php echo $this->baseUrl('/curso/empreendedor'); ?>" title="Emprrendedor Pearson">Empreendedor Pearson</a></li>
            <?php 
      			foreach($this->extensionCourses as $course) : 
      			if(strlen($course->name) > 40)
      			{
      				$courseName = substr($course->name, 0, 37) . '...';
      			} else
      			{
      				$courseName = $course->name;
      			}
      		?>
      		<li><a href="<?php echo $this->baseUrl('/curso/extensao/' . $course->idcourse . ',,' . urlencode($course->name)); ?>" title="<?php echo $course->name; ?>"><?php echo $courseName; ?></a></li>
      		<?php 
      			endforeach; 
      		?>
           </ul>
    </div>
   
       <div id="pos-grad">
         <div id="title-footer">Pós-Graduação</div>
            <ul class="menu3">
            	<?php 
            		foreach($this->posgraduationCourses as $course) :
            		if(strlen($course->name) > 40)
            		{
            			$courseName = substr($course->name, 0, 37) . '...';
            		} else
            		{
            			$courseName = $course->name;
            		}
            	?>
            	<li><a href="<?php echo $this->baseUrl('/posgraduacao/' . $course->idposgraduation . ',,' . urlencode($course->name)); ?>" title="<?php echo $course->name; ?>"><?php echo $courseName; ?></a></li>
            	<?php 
            		endforeach; 
            	?>
            </ul>
       </div>
       
    <div id="footer-detail">
      <table width="220" height="220" border="0" align="right">
        <tr>
          <td><span class="tel">(15) 3034-9400</span><br />
            <span class="endereco">Rua M&aacute;rio Campestrini, 100<br />
            Parque Campolim, Sorocaba - SP</span></td>
        </tr>
        <tr>
          <td align="right" valign="bottom"><a href="http://www.aplustec.com.br" target="_blank"><img src="<?php $this->asset('logoaplus.png','imagens'); ?>" width="40" height="24" border="0" /></a></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<?php if($this->currentAction == 'contact') : ?>
<script type="text/javascript">
var sprytextfield1 = new Spry.Widget.ValidationTextField("sprytextfield1", "none", {validateOn:["blur"]});
var sprytextfield2 = new Spry.Widget.ValidationTextField("sprytextfield2", "email", {validateOn:["blur"]});
var sprytextfield3 = new Spry.Widget.ValidationTextField("sprytextfield3", "custom", {pattern:"xx xxxx-xxxx", hint:"(DDD) Telefone", useCharacterMasking:true, validateOn:["blur"]});
var sprytextfield4 = new Spry.Widget.ValidationTextField("sprytextfield4", "none", {validateOn:["blur"]});
var sprytextarea1 = new Spry.Widget.ValidationTextarea("sprytextarea1", {validateOn:["blur"]});
</script>
<?php endif; ?>

</body>
</html>