<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Faculdade Ipanema - Formando l&iacute;deres completos!</title>
<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:300' rel='stylesheet' type='text/css'>
<link href="<?php $this->asset('template.css','css'); ?>" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<?php $this->asset('menu.css','css'); ?>" type="text/css" media="screen" />
<link href="<?php $this->asset('class.css','css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('form.css','css'); ?>" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<?php $this->asset('nivo-slider.css','banner'); ?>" type="text/css" media="screen"/>
<link rel="stylesheet" href="<?php $this->asset('style.css','banner'); ?>" type="text/css" media="screen"/>
<link rel="stylesheet" type="text/css" href="<?php $this->asset('jquery.fancybox.css','fancy/css'); ?>" media="screen" />

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
    <script type="text/javascript" src="<?php $this->asset('jquery-1.4.3.min.js','banner/scripts'); ?>"></script>
    <script type="text/javascript" src="<?php $this->asset('jquery.fancybox.js','fancy/js'); ?>"></script>
    <script type="text/javascript" src="<?php $this->asset('control.js','fancy/js'); ?>"></script>

    
<?php if($this->currentAction == 'doubts') : ?>
<link href="<?php $this->asset('faq.css','css'); ?>" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php $this->asset('jquery-ui-1.8.16.js','js'); ?>"></script>
<script type="text/javascript" src="<?php $this->asset('functions.js','js'); ?>"></script>
<?php endif; ?>

<?php if($this->currentAction == 'contact') : ?>
<script src="<?php $this->asset('SpryValidationTextField.js','SpryAssets'); ?>" type="text/javascript"></script>
<script src="<?php $this->asset('SpryValidationTextarea.js','SpryAssets'); ?>" type="text/javascript"></script>
<link href="<?php $this->asset('SpryValidationTextField.css','SpryAssets'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('SpryValidationTextarea.css','SpryAssets'); ?>" rel="stylesheet" type="text/css" />
<?php endif; ?>
    

<script type="text/javascript" src="<?php $this->asset('jquery.nivo.slider.js','banner/scripts'); ?>"></script>
   
   <script type="text/javascript">
     $(window).load(function() {
     $('#slider').nivoSlider();
     });
   </script>

<?php if($this->currentController == 'news') : ?>
<link href="<?php $this->asset('nav.css','css'); ?>" rel="stylesheet" type="text/css" />
<?php endif; ?>

<?php if($this->currentController == 'media') : ?>
<link href="<?php $this->asset('nav.css','css'); ?>" rel="stylesheet" type="text/css" />
<?php endif; ?>

<script type="text/javascript">
var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12375493-42']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
</script>

<script type="text/javascript">
	function goToUrl( url )
	{
		window.location.href = url;
	}
</script>

<script type="text/javascript">
	function sendForm()
	{
		document.getElementById('vestibuForm').submit();
	}
</script>

<?php echo $this->alerts(); ?>

</head>

<body>

<div style="display: none;">
		<div id="inline1" style="width:240px;">
			<h3>Portal Acadêmico</h3>
<form name="log" id="log" action="http://www.aspescola.com.br/app/appAuth" target="_blank" method="post">

<INPUT type="hidden" name="txt_CdInstituicao" id="txt_CdInstituicao" value="225">
<INPUT type="hidden" name="txt_IdModulo" id="txt_IdModulo" value="2">
<br><br>
<span class="label">Usuário:</span><br><INPUT name="j_username" type="text" class="input2" id="j_username" size="38"><br><br>
<span class="label">Senha:</span><br><INPUT type="password"name="j_password" class="input2" id="j_password" size="38"><br><br>
<span class="label">Resposta secreta:</span><br><INPUT name="txt_DsRespostaSecreta" type="password" class="input2" id="txt_DsRespostaSecreta" size="38"><br><br>
<span class="label">Tipo de usuário:</span><br>
<select name="txt_IdTipoUsuario" class="select-login" id="txt_IdTipoUsuario" onchange="setOptions2(document.log.txt_IdTipoUsuario.options[document.log.txt_IdTipoUsuario.selectedIndex].value);">
    <option value="3">Aluno</option>
    <option value="2">Professor</option>
  </select><br><br><br>
<INPUT name="submit" type="submit" class="bt2" value=" ACESSAR PORTAL ">
</form>

  </div>
	</div>

<div id="container-header">
  <div id="header">
    <div id="logo"><a href="<?php echo $this->baseUrl('/'); ?>"><img src="<?php $this->asset('logo.png','imagens'); ?>" height="120" border="0" title="Página Inicial" /></a></div>
    <div id="detail-header">
      <div id="social">
        <table width="300" border="0" align="right">
          <tr>
            <td width="166" height="50" valign="bottom"><a class="fancybox" href="#inline1"><img src="<?php $this->asset('potal.png','imagens'); ?>" width="150" height="36" border="0" title="Portal Acadêmico" /></a></td>
            <td width="124" align="right" valign="bottom"><a href="http://www.facebook.com/FaculdadeIpanema" target="_blank"><img src="<?php $this->asset('ico-facebook.png','imagens'); ?>" width="26" height="26" border="0" title="Facebook" /></a>&nbsp;&nbsp; <a href="http://twitter.com/EstudenaIpanema" target="_blank"><img src="<?php $this->asset('ico-twitter.png','imagens'); ?>" width="26" height="26" border="0" title="Twitter" /></a>&nbsp;&nbsp; <a href="https://www.youtube.com/channel/UC2XhpVfj0sBMAyIyoqMdEMw" target="_blank"><img src="<?php $this->asset('ico-youtube.png','imagens'); ?>" width="26" height="26" border="0" title="YouTube" /></a></td>
          </tr>
        </table>
      </div>
      <div id="naveg">
        
        <?php echo $this->render('menu.phtml'); ?>
      
      </div>
    </div>
  </div>
</div>