<ul id="menu">

	<li class="menu_left"><a href="#" class="drop">A IPANEMA</a>
		<div class="dropdown_1column align_right">
			<div class="col_1">
				<ul class="simple">
					<li><a href="<?php echo $this->baseUrl('/conheca'); ?>" title="Conheça a Ipanema">Conheça a Ipanema</a></li>
					<li><a href="<?php echo $this->baseUrl('/estrutura'); ?>" title="Estrutura">Estrutura</a></li>
					<li><a href="<?php echo $this->baseUrl('/comoingressar'); ?>" title="Como Ingressar">Como Ingressar</a></li>
					<li><a href="<?php echo $this->baseUrl('/noticias'); ?>" title="Notícias">Notícias</a></li>
				</ul>
			</div>
		</div>
	</li>
	
	<li><a href="#" class="drop">CURSOS</a>
		<div class="dropdown_4columns">
			<div class="col_1">
				<h3>Graduação</h3>
				<ul>
					<?php 
						foreach($this->graduationCourses as $course) :
						if(strlen($course->name) > 40)
						{
							$courseName = substr($course->name, 0, 37) . '...';
						} else
						{
							$courseName = $course->name; 
						}
					?>
					<li><a href="<?php echo $this->baseUrl('/graduacao/' . $course->idgraduation . ',,' . urlencode($course->name)); ?>" title="<?php echo $course->name ; ?>"><?php echo $courseName; ?></a></li>
					<?php 
						endforeach; 
					?>
				</ul>
			</div>
			
			<div class="col_2">
				<h3>Pós Graduação</h3>
				<ul>
					<?php 
						foreach($this->posgraduationCourses as $course) :
						if(strlen($course->name) > 40)
						{
							$courseName = substr($course->name, 0, 37) . '...';
						} else
						{
							$courseName = $course->name;
						}
					?>
					<li><a href="<?php echo $this->baseUrl('/posgraduacao/' . $course->idposgraduation . ',,' . urlencode($course->name)); ?>" title="<?php echo $course->name; ?>"><?php echo $courseName; ?></a></li>
					<?php 
						endforeach; 
					?>
				</ul>
			</div>
			
			<div class="col_1">
				<h3>Idiomas e Extensão</h3>
				<ul>
					<li><a href="<?php echo $this->baseUrl('/curso/idiomas'); ?>" title="Speak Centro de Idiomas">Speak Centro de Idiomas</a></li>
					<li><a href="<?php echo $this->baseUrl('/curso/empreendedor'); ?>" title="Empreendedor Pearson">Empreendedor Pearson</a></li>
					<?php 
						foreach($this->extensionCourses as $course) :
						if(strlen($course->name) > 40)
						{
							$courseName = substr($course->name, 0, 37) . '...';
						} else
						{
							$courseName = $course->name;
						}
					?>
					<li><a href="<?php echo $this->baseUrl('/curso/extensao/' . $course->idcourse . ',,' . urlencode($course->name)); ?>" title="<?php echo $course->name; ?>"><?php echo $courseName; ?></a></li>
					<?php 
						endforeach;
					?>
				</ul>
			</div>
		</div>
	</li>
	
	<li><a href="<?php echo $this->baseUrl('/vestibular'); ?>" title="Vestibular">VESTIBULAR</a></li>
	
	<li><a href="<?php echo $this->baseUrl('/inscrevase'); ?>" title="Inscreva-se">INSCREVA-SE</a></li>
	
	<li><a href="<?php echo $this->baseUrl('/tvipanema'); ?>" title="TV Ipanema">TV IPANEMA</a></li>
	
	<li><a href="<?php echo $this->baseUrl('/duvidas'); ?>" title="Dúvidas">DÚVIDAS</a></li>
	
	<li><a href="<?php echo $this->baseUrl('/contato'); ?>" title="Fale Conosco">FALE CONOSCO</a></li>
	
</ul>