<?php echo $this->render('header.phtml'); ?>

<div id="container2">
  <div id="title">P&aacute;gina Vestibular</div>
  <div id="formulario">
      <form id="form1" name="form1" method="post" action="" enctype="multipart/form-data">
    <table width="1019" border="0">
      <tr>
        <td height="30" valign="bottom" class="label">T&iacute;tulo da p&aacute;gina</td>
      </tr>
      <tr>
        <td height="30" valign="bottom"><label for="titulo"></label>
          <input name="title" type="text" class="input" id="titulo" /></td>
      </tr>
      <tr>
        <td height="30" valign="bottom"><span class="label">Imagem</span></td>
      </tr>
      <tr>
        <td><input name="image1" type="file" id="image1" />
        <label><em><span class="info">(750 x 500px Arquivo - JPG)</span></em></label></td>
      </tr>
      <tr>
        <td height="45"><input name="cadastrar" type="submit" class="bt" id="cadastrar" value="Atualizar" /></td>
      </tr>
    </table>
    <br />
    </form>


  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>