<?php echo $this->render('header.phtml'); ?>

<div id="container2">
  <div id="title">Editar Curso Gradua&ccedil;&atilde;o</div>
  <div id="formulario">
    <br />
    <form id="form1" name="form1" method="post" action="">
    <table width="1005" border="0">
      <tr>
        <td height="30" colspan="3" valign="bottom"><span class="label">Nome do curso</span></td>
      </tr>
      <tr>
        <td colspan="3"><label for="titulo"></label><input name="name" type="text" class="input" id="titulo" value="<?php echo $this->graduation->name; ?>" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Descri&ccedil;&atilde;o do curso</td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom"><label for="texto"></label>
          <textarea name="description" cols="45" rows="5" class="area2" id="texto"><?php echo $this->graduation->description; ?></textarea></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom"><span class="label">M&Eacute;DIA DE REMUNERA&Ccedil;&Atilde;O PARA PROFISSIONAL REC&Eacute;M-FORMADO</span></td>
      </tr>
      <tr>
        <td colspan="3">&nbsp;</td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Empresa de grande porte</td>
      </tr>
      <tr>
        <td colspan="3"><label for="grande-porte"></label>
          <input name="bigenterprise" type="text" class="input2" id="grande-porte" value="<?php echo $this->graduation->remuneration_bigenterprise; ?>" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Empresa de pequeno porte</td>
      </tr>
      <tr>
        <td colspan="3"><label for="pequeno-porte"></label>
          <input name="middleenterprise" type="text" class="input2" id="pequeno-porte" value="<?php echo $this->graduation->remuneration_middleenterprise; ?>" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3">&nbsp;</td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Per&iacute;odo</td>
      </tr>
      <tr>
        <td height="30" colspan="3"><label for="periodo"></label>
          <input name="period" type="text" class="input2" id="periodo" value="<?php echo $this->graduation->period; ?>" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Dura&ccedil;&atilde;o do curso</td>
      </tr>
      <tr>
        <td height="30" colspan="3"><label for="duracao"></label>
          <input name="duration" type="text" class="input2" id="duracao" value="<?php echo $this->graduation->duration; ?>" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Vagas</td>
      </tr>
      <tr>
        <td height="30" colspan="3"><label for="vagas"></label>
          <input name="vacancies" type="text" class="input2" id="vagas" value="<?php echo $this->graduation->vacancies; ?>" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Mensalidade</td>
      </tr>
      <tr>
        <td height="30" colspan="3"><label for="mensalidade"></label>
          <input name="price" type="text" class="input2" id="mensalidade" value="<?php echo $this->graduation->price; ?>" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3">&nbsp;</td>
      </tr>
      <tr>
        <td height="45" colspan="3" class="label">GRADE CURRICULAR</td>
      </tr>
      
      <?php 
      for($i=1;$i<=$this->countModules;$i++) :
      	$module = $this->modules->current(); 
      	$components = $this->getComponentsOfModule($module->idmodule);
      ?>
      <input type="hidden" name="module_<?=$i;?>_idmodule" id="module_<?=$i;?>_idmodule" value="<?php echo $module->idmodule; ?>" />
      <tr>
        <td height="30" colspan="3" class="label">M&oacute;dulo <?php echo $this->inRoman($i); ?></td>
      </tr>
      <tr>
        <td height="30" colspan="3" class="label">Nome</td>
      </tr>
      <tr>
        <td height="30" colspan="3"><label for="nomemod"></label>
          <input name="module_<?=$i;?>_name" type="text" class="input" id="nomemod" value="<?php echo $module->name; ?>" /></td>
      </tr>
      <tr>
        <td width="476" height="30" class="label">Componentes</td>
        <td width="159" class="label">Carga Hor. Semanal</td>
        <td width="265" class="label">Carga Hor Semestral</td>
      </tr>
      <?php 
      for($j=1;$j<=$this->countComponents;$j++) : 
      	$component = $components->current();
      ?>
      <input type="hidden" name="module_<?=$i;?>_component_<?=$j;?>_idcomponent" id="module_<?=$i;?>_component_<?=$j;?>_idcomponent" value="<?php echo $component->idcomponent; ?>" />
      <tr>
        <td height="30"><label for="comp"></label>
          <input name="module_<?=$i;?>_component_<?=$j;?>_name" type="text" class="input" id="comp" value="<?php echo $component->name; ?>" /></td>
        <td height="30"><label for="cargasn"></label>
          <input name="module_<?=$i;?>_component_<?=$j;?>_weekly_workload" type="text" class="input2" id="cargasn" value="<?php echo $component->weekly_workload; ?>" /></td>
        <td height="30"><input name="module_<?=$i;?>_component_<?=$j;?>_semester_hours" type="text" class="input2" id="cargasn10" value="<?php echo $component->semester_hours; ?>" /></td>
      </tr>
      <?php
      	$components->next(); 
      endfor; 
      ?>
      <tr>
        <td height="30" align="right" class="label">Total</td>
        <td height="30"><input name="module_<?=$i;?>_weekly_workload" type="text" class="input2" id="cargasn19" value="<?php echo $module->weekly_workload; ?>" /></td>
        <td height="30"><input name="module_<?=$i;?>_semester_hours" type="text" class="input2" id="cargasn20" value="<?php echo $module->semester_hours; ?>" /></td>
      </tr>
      <tr>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
      </tr>
      <?php
      	$this->modules->next(); 
      endfor;
      ?>
      
      <tr>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
      </tr>
      <tr>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
      </tr>
      <tr>
        <td height="45" colspan="3"><input name="cadastrar" type="submit" class="bt" id="cadastrar" value="Cadastrar" /></td>
      </tr>
    </table>
    <br />
    </form>  
  
    
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>