<?php echo $this->render('header.phtml'); ?>

<div id="container">
  <div id="content5">
      <div id="block-content5">
       <h2>Speak Centro de Idiomas</h2>
       <span class="type">Idiomas e Extens&atilde;o</span>
       <h3>
       <br />
       <br />
       Sempre com o objetivo em criar líderes completos, a Faculdade Ipanema traz mais uma inovação para o ensino superior de Sorocaba: o Speak Centro de Idiomas. O Speak é mais nova forma de aprender inglês de forma inteligente. Formado por profissionais de altíssimo nível e, em um curso ministrado totalmente em inglês, nossos alunos e a comunidade poderão contar com mais esta ferramenta para seu desenvolvimento pessoal e profissional.
       <br />
       <br />
       Com mais esta possibilidade de aperfeiçoamento, o nosso aluno mais uma vez garante sua excelência profissional ao sair de nossas salas de aula para o mercado. É a Faculdade Ipanema analisando seu aluno em 360 graus e preparando-o ao máximo para o mercado de trabalho!
       <br />
       <br />
       <br />
       <span class="subtitlte">Metodologia e Material Didático
       </span><br />
       <br />
       Utilizamos metodologia diferenciada. Um curso voltado para o business, totalmente ensinado em inglês, desde o primeiro dia. Afinal, acreditamos que a melhor forma de alfabetizar, foi da forma que aprendemos: escutando e falando em inglês!
       <br />
       <br />
       Nosso material didático foi rigorosamente escolhido, utilizando as seguintes perguntas:
       <br />
       <br />
       •	O material é contemporâneo?
       <br />
       •	O material é ilustrado?
       <br />
       •	A editora possui qualidade reconhecida?
       <br />
       •	Possui integração livro x multimídia?
       <br />
       <br />
       Com estas perguntas respondidas positivamente, chegamos ao nosso material didático, totalmente desenvolvido pela Pearson Education, uma das maiores editoras do mundo e de alta performance em livros de conteúdo em inglês e outras línguas.
       <br />
       <br />
       Nossos professores estão orientados à utilizar o que há de mais contemporâneo para o ensino das diversas línguas de forma agradável. Sessão pipoca, música ao ar livre e séries de TV são algumas das formas muito utilizadas para que possamos ter o melhor aproveitamento por parte de nossos alunos.
       <br />
       <br />
       <br />
       <span class="subtitlte">O Curso</span><br />
       <br />
       O curso é distribuído em 4 grandes módulos: Básico, Pré Intermediário, Intermediário e Avançado. Cada módulo é composto por 120 horas, distribuídas em um ano. 
       <br />
       <br />
       Nosso aluno será avaliado por bimestres, realizando 4 provas anuais pré estabelecidas em nosso calendário acadêmico. Para o aluno passar para o próximo módulo, o mesmo deverá possuir uma aprovação de 70%.
       <br />
       <br />
       Ao final de cada módulo, o aluno terá direito ao seu certificado de conclusão de módulo. No final do curso, nosso aluno será submetido à um teste oficial e reconhecido internacionalmente onde, se aprovado, o mesmo terá em seu currículo um certificado internacional em idiomas.
       <br />
       <br />
       <br />
       <span class="subtitlte">Cursos In Company </span><br />
       <br />
       Seguindo as tendências mundiais, a Faculdade Ipanema através da Speak, seu centro de idiomas, oferece turmas in company para o aprendizado do inglês sem sair da empresa. Entre em contato com o nosso setor comercial através do telefone <strong>3034-9000</strong> para maiores detalhes. </h3>
      </div>
    
    <?php echo $this->render('course/sidebar.phtml'); ?>
  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>