<?php echo $this->render('header.phtml'); ?>

<div id="container2">
  <div id="title">Cadastrar Curso P&oacute;s-Gradua&ccedil;&atilde;o</div>
  <div id="formulario">
    <br />
    <form id="form1" name="form1" method="post" action="">
    <table width="1005" border="0">
      <tr>
        <td height="30" colspan="3" valign="bottom"><span class="label">Nome do curso</span></td>
      </tr>
      <tr>
        <td colspan="3"><label for="titulo"></label><input name="name" type="text" class="input" id="titulo" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom"><span class="label">Mensalidade</span></td>
      </tr>
      <tr>
        <td colspan="3"><label for="mensalidade"></label><input name="price" type="text" class="input" id="mensalidade" /></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Objetivos</td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom"><label for="texto"></label>
          <textarea name="objective" cols="45" rows="5" class="area2" id="texto"></textarea></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">&Aacute;rea de atua&ccedil;&atilde;o</td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom"><label for="area"></label>
          <textarea name="area" cols="45" rows="5" class="area2" id="area"></textarea></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">P&uacute;blico alvo</td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom"><label for="texto3"></label>
          <textarea name="public" cols="45" rows="5" class="area2" id="texto3"></textarea></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Metodologia</td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom"><label for="texto6"></label>
          <textarea name="metodology" cols="45" rows="5" class="area2" id="texto6"></textarea></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom" class="label">Avalia&ccedil;&atilde;o</td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom"><label for="texto4"></label>
          <textarea name="avaliation" cols="45" rows="5" class="area2" id="texto4"></textarea></td>
      </tr>
      <tr>
        <td height="30" colspan="3" valign="bottom">&nbsp;</td>
      </tr>
      <tr>
        <td width="476" height="30" class="label">Componentes Curriculares</td>
        <td width="159" class="label">&nbsp;</td>
        <td width="265" class="label">&nbsp;</td>
      </tr>
      
      <?php for($i=1;$i<=$this->components;$i++):?>
      <tr>
        <td height="30"><label for="component_<?=$i;?>_name"></label>
          <input name="component_<?=$i;?>_name" type="text" class="input" id="component_<?=$i;?>_name" /></td>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
      </tr>
      <?php endfor; ?>
      <tr>
        <td height="30" align="right" class="label">&nbsp;</td>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
      </tr>
      <tr>
        <td height="30"><span class="label">Total carga hor&aacute;ria</span></td>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
      </tr>
      <tr>
        <td height="30"><label for="carga"></label>
          <input name="workload" type="text" class="input2" id="carga" /></td>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
      </tr>
      <tr>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
        <td height="30">&nbsp;</td>
      </tr>
      <tr>
        <td height="45" colspan="3"><input name="cadastrar" type="submit" class="bt" id="cadastrar" value="Cadastrar" /></td>
      </tr>
    </table>
    <br />
    </form>  
  
    
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>