<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Faculdade Ipanema</title>
<link href="<?php $this->asset('template.css','css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('form.css','css'); ?>" rel="stylesheet" type="text/css" />

<?php echo $this->alerts(); ?>

</head>

<body>
<div id="total2">
  <form id="form1" name="form1" method="post" action="<?php echo $this->baseUrl('/auth'); ?>">
    <br />
    <table width="206" align="center">
      <tr>
        <td width="198" height="40" valign="top" class="admin">Faculdade Ipanema</td>
      </tr>
      <tr>
        <td class="titulo"><span class="label">Nome de Usu&aacute;rio</span></td>
      </tr>
      <tr>
        <td class="titulo"><input name="username" type="text" class="input3" id="usuario" /></td>
      </tr>
      <tr>
        <td height="30" valign="bottom" class="titulo"><span class="label">Senha</span></td>
      </tr>
      <tr>
        <td class="titulo"><input name="password" type="password" class="input3" id="senha" /></td>
      </tr>
      <tr>
        <td height="40" align="right"><input name="entrar" type="submit" class="bt2" id="entrar" value="Login" /></td>
      </tr>
    </table>
  </form>
</div>
</body>
</html>