<?php

/**
 * @see Zend_View_Helper_Abstract
 */
require_once 'Zend/View/Helper/Abstract.php';

/**
 * This is a Zend View Helper for show alerts stored in FlashMessenger Action Helper
 * 
 * @category Helpers
 * @package App/Modules/Default/Views
 * @subpackage Helpers
 * @author Lucas Mendes de Freitas (devsdmf)
 * @since 2012
 * @license http://www.devsdmf.net/license/general.txt
 * @copyright Aplus Tecnologia e Engenharia LTDA | devSDMF Software Development (c)
 *
 */

class Zend_View_Helper_Alerts extends Zend_View_Helper_Abstract
{
	/**
	 * The Script generated by object 
	 * 
	 * @var string
	 */
	protected $_script = null;
	/**
	 * The method to render the script
	 * 
	 * @return string
	 */
	function alerts()
	{
		if($this->view->flashMessengerAlerts != null)
		{
			$this->_script = '<script type="text/javascript">';
			foreach($this->view->flashMessengerAlerts as $alert)
			{
				$this->_script .= 'alert("' . $alert . '");';
			}
			$this->_script .= '</script>';
		}
		
		return $this->_script;
	}
}