<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Faculdade Ipanema</title>
<link href="<?php $this->asset('template.css','css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('superfish.css','menu/css'); ?>" rel="stylesheet" type="text/css" media="screen" />
<link href="<?php $this->asset('style.css','menu/css'); ?>" rel="stylesheet" type="text/css" />
<link id="textContentCss" href="<?php $this->asset('menu-text-01-Default.css','menu/css'); ?>" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?php $this->asset('jquery.fancybox.css','fancy/css'); ?>" media="screen" />
<link href="<?php $this->asset('form.css','css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('nav.css','css'); ?>" rel="stylesheet" type="text/css" />

<?php if($this->currentController == 'gallery') { echo $this->render('gallery/headers.phtml'); } ?>

<?php if($this->currentController == 'news') { echo $this->render('news/headers.phtml'); } ?>

<?php if($this->currentController == 'extension') { echo $this->render('extension/headers.phtml'); } ?>
   
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
<script language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript" src="<?php $this->asset('jquery.fancybox.js','fancy/js'); ?>"></script>
<script type="text/javascript" src="<?php $this->asset('control.js','fancy/js'); ?>"></script>

<script src="<?php $this->asset('superfish.js','menu/js'); ?>" type="text/javascript"></script>
<script src="<?php $this->asset('scriptsInit.js','menu/js'); ?>" type="text/javascript"></script>

<?php echo $this->alerts(); ?>

        
        
<link href="<?php $this->asset('tabela.css','css'); ?>" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header">
<div id="topo">
  <h1>Faculdade Ipanema</h1>
</div>

<div id="menu">

  <?php echo $this->render('menu.phtml'); ?>    

  </div>
</div>