	<ul class="sf-menu">
    	<li>
    		<a href="<?php echo $this->baseUrl('/admin'); ?>">PRINCIPAL</a>
    	</li>
    	
    	<li>
        	<a href="#">BANNER</a>
        	<ul>
        		<li><a href="<?php echo $this->baseUrl('/admin/banner'); ?>">Ver banners</a></li>
        		<li><a href="<?php echo $this->baseUrl('/admin/banner/new'); ?>">Novo banner</a></li>
        	</ul>
        </li>
        
        <li>
        	<a href="#">CURSOS</a>
        	<ul>
        		<li><a href="<?php echo $this->baseUrl('/admin/graduation'); ?>">Graduação</a></li>
        		<li><a href="<?php echo $this->baseUrl('/admin/posgraduation'); ?>">Pós-Graduação</a></li>
        		<li><a href="<?php echo $this->baseUrl('/admin/extension'); ?>">Idiomas e Extensão</a></li>
        	</ul>
        </li>
        
        <li>
        	<a href="#">VESTIBULAR</a>
        	<ul>
        		<li><a href="<?php echo $this->baseUrl('/admin/page/process'); ?>">Gerenciar vestibular</a></li>
        		<li><a href="<?php echo $this->baseUrl('/admin/process'); ?>">Processo Seletivo</a></li>
        	</ul>
        </li>
        
        <li>
        	<a href="#">GALERIA</a>
        	<ul>
        		<li><a href="<?php echo $this->baseUrl('/admin/gallery'); ?>">Ver álbuns</a></li>
        		<li><a href="<?php echo $this->baseUrl('/admin/gallery/new'); ?>">Novo álbum</a></li>
        	</ul>
        </li>
        
        <li>
        	<a href="#">DUVIDAS</a>
        	<ul>
        		<li><a href="<?php echo $this->baseUrl('/admin/doubts'); ?>">Ver dúvidas</a></li>
        		<li><a href="<?php echo $this->baseUrl('/admin/doubts/new'); ?>">Nova dúvida</a></li>
        	</ul>
        </li>
        
        <li>
        	<a href="#">VÍDEOS</a>
        	<ul>
        		<li><a href="<?php echo $this->baseUrl('/admin/video'); ?>">Ver vídeos</a></li>
        		<li><a href="<?php echo $this->baseUrl('/admin/video/new'); ?>">Novo vídeo</a></li>
        	</ul>
        </li>
        
        <li>
        	<a href="#">NOTÍCIAS</a>
        	<ul>
        		<li><a href="<?php echo $this->baseUrl('/admin/news'); ?>">Ver notícias</a></li>
        		<li><a href="<?php echo $this->baseUrl('/admin/news/new'); ?>">Nova notícia</a></li>
        	</ul>
        </li>
        
        <li>
        	<a href="#">CONFIGURAÇÃO</a>
        	<ul>
        		<li><a href="<?php echo $this->baseUrl('/admin/settings/password'); ?>">Alterar senha</a></li>
        	</ul>
        </li> 
        
        <li>
        	<a href="<?php echo $this->baseUrl('/logout'); ?>">SAIR</a>
        </li>
	</ul>