<?php echo $this->render('header.phtml'); ?>

<div id="container3">
  <div id="title">Alterar senha de acesso</div>
  <div id="vitrine">
    <br />
    <form id="form1" name="form1" method="post" action="">
    <table width="400" border="0" cellpadding="5">
    <tr>
      <td width="216" height="30" class="label">Senha antiga</td>
      </tr>
    <tr>
      <td height="30"><label for="senha"></label>
        <input name="oldpass" type="password" class="input" id="senha" /></td>
      </tr>
    <tr>
      <td height="30" class="label">Nova senha</td>
      </tr>
    <tr>
      <td height="30"><label for="senha2"></label>
        <input name="newpass" type="password" class="input" id="senha2" /> 
        <em><span class="info">M&aacute;x 8 caracteres.</span></em></td>
      </tr>
    <tr>
      <td height="30" ><input name="alterar" type="submit" class="bt" id="alterar" value="Alterar" /></td>
    </tr>
    </table>
      </form>  
  
    
</div>
</div>

<?php echo $this->render('footer.phtml'); ?>