<?php echo $this->render('header.phtml'); ?>

<div id="container">
  <div id="content3">
      <div id="block-content3">
       <h2>D&uacute;vidas</h2>
       <h3>
         Você não tem dúvidas de que inovação é a melhor escolha para o seu futuro, né? Mas para esclarecer dúvidas sobre a Faculdade Ipanema ou sobre o vestibular, listamos aqui alguns tópicos que podem ajudar.
       </h3>
       <div id="accordion">
						<div>
							<h3><a href="#">1. Onde é a Faculdade?</a></h3>
							<div>
								A Faculdade Ipanema compartilha a excelente estrutura do Colégio Ser, localizado à <b>Rua Mário Campestrini, 100, Parque Campolim. Sorocaba, SP</b>.
							</div>
						</div>
						<div>
							<h3><a href="#">2. Qual o horário de funcionamento?</a></h3>
							<div>
								<b>Comercial:</b> de 10h às 19h<br/>
								<b>Secretaria:</b> de 13h às 22h<br/>
								<b>Biblioteca:</b> de 18h às 22h<br/>
								<b>Diretoria:</b> de 18h às 22h
							</div>
						</div>
						<div>
							<h3><a href="#">3. A Faculdade Ipanema pertence a algum grande grupo educacional?</a></h3>
							<div>
								A Faculdade Ipanema surgiu da iniciativa de executivos com duas décadas de atuação no setor de Educação, entusiastas de inovações tecnológicas e apaixonados pelo poder transformador da liderança colaborativa.<br/><br/>O que nos move é a crença de que as instituições de ensino superior atualmente não mantêm um modelo de ensino que forme líderes completos em todos os aspectos que consideramos fundamentais para a real liderança.
							</div>
						</div>
						<div>
							<h3><a href="#">4. Quais os cursos ofertados?</a></h3>
							<div>
								<table  border="0" cellspacing="0" cellpadding="0">
									<tr>
										<td class="bg"><b>Nome do Curso</b></td>
										<td class="bg"><b>Modalidade</b></td>
										<td class="bg"><b>Duração</b></td>
										<td class="bg"><b>Vagas</b></td>
										<td class="bg"><b>Mensalidade</b></td>
										<td class="bg"><b>Dia /<br/>Horário de aulas</b></td>
									</tr>
									<tr>
										<td class="line">Gestão de Recursos Humanos</td>
										<td class="line">Graduação</td>
										<td class="line">4 semestres</td>
										<td class="line" align="center">100</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">2a a 6a<br/>19h às 22h40</td>
									</tr>
									<tr>
										<td class="line">Gestão Financeira</td>
										<td class="line">Graduação</td>
										<td class="line">4 semestres</td>
										<td class="line" align="center">100</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">2a a 6a<br/>19h às 22h40</td>
									</tr>
									<tr>
										<td class="line">Processos Gerenciais</td>
										<td class="line">Graduação</td>
										<td class="line">4 semestres</td>
										<td class="line" align="center">100</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">2a a 6a<br/>19h às 22h40</td>
									</tr>
									<tr>
										<td class="line">Marketing</td>
										<td class="line">Graduação</td>
										<td class="line">4 semestres</td>
										<td class="line" align="center">100</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">2a a 6a<br/>19h às 22h40</td>
									</tr>
									<tr>
										<td class="line">MBA em Mercado de Capitais</td>
										<td class="line">MBA</td>
										<td class="line">18 meses<br/>432 horas-aula</td>
										<td class="line" align="center">30</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">2a e 4a<br/>19h às 22h40</td>
									</tr>
									<tr>
										<td class="line">MBA em Redes Sociais e Inovação Digital</td>
										<td class="line">MBA</td>
										<td class="line">18 meses<br/>432 horas-aula</td>
										<td class="line" align="center">30</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">2a e 4a<br/>19h às 22h40</td>
									</tr>
									<tr>
										<td class="line">MBA em Marketing de Serviços</td>
										<td class="line">MBA</td>
										<td class="line">18 meses<br/>432 horas-aula</td>
										<td class="line" align="center">30</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">3a e 5a<br/>19h às 22h40</td>
									</tr>
									<tr>
										<td class="line">MBA em Gestão Estratégica de Pessoas</td>
										<td class="line">MBA</td>
										<td class="line">18 meses<br/>432 horas-aula</td>
										<td class="line" align="center">30</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">3a e 5a<br/>19h às 22h40</td>
									</tr>
									<tr>
										<td class="line">>Pós em Gestão Educacional</td>
										<td class="line">Pós-Graduação</td>
										<td class="line">18 meses<br/>432 horas-aula</td>
										<td class="line" align="center">30</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">6as de 19h às 22h40<br/>Sáb de 8h às 12h</td>
									</tr>
									<tr>
										<td class="line">Pós em Psicopedagogia Clínica</td>
										<td class="line">Pós-Graduação</td>
										<td class="line">24 meses<br/>600 horas-aula</td>
										<td class="line" align="center">30</td>
										<td class="line">vide promoção de lançamento*</td>
										<td class="line">6as de 19h às 22h40<br/>Sáb de 8h às 12h</td>
									</tr>
								</table>
							</div>
						</div>
						<div>
							<h3><a href="#">5. E o valor das mensalidades?</a></h3>
							<div>
								*PARA PRESENTEAR A CIDADE DE SOROCABA EM NOSSO LANÇAMENTO, TODOS OS ALUNOS MATRICULADOS <b>ATÉ 29/02/12</b> RECEBERÃO BOLSA DE <b>50%</b> VÁLIDA PARA TODO O CURSO. ESTA PROMOÇÃO É VÁLIDA PARA GRADUAÇÃO E PARA PÓS-GRADUAÇÃO<br/><br/>
								<b>Graduação:</b> mensalidade de <span style="text-decoration:line-through;">R$799</span> por <b>R$399,50</b><br/>
								<b>Pós-Graduação:</b> mensalidade de <span style="text-decoration:line-through;">R$674</span> por <b>R$377,00</b>**<br/><br/>
								*Promoção de Lançamento<br/>
								**No plano de pagamento de 24 vezes<br/><br/>
								Os planos de pagamento da pós-graduação estão detalhados no quadro abaixo:<br/><br/>
								<table border="0" cellspacing="0" cellpadding="0">
									<tr>
										<td class="bg"><b>Nome do Curso</b></td>
										<td class="bg"><b>Data de Início</b></td>
										<td class="bg"><b>Valor Promocional<br/>(50% de desconto)</b></td>
										<td class="bg"><b>24x</b></td>
										<td class="bg"><b>18x</b></td>
										<td class="bg"><b>12x</b></td>
									</tr>
									<tr>
										<td class="line">MBA em Mercado de Capitais</td>
										<td class="line">05/03/2012</td>
										<td class="line">R$ 8.091</td>
										<td class="line">R$ 337</td>
										<td class="line">R$ 450</td>
										<td class="line">R$ 675</td>
									</tr>
									<tr>
										<td class="line">MBA em Redes Sociais e Inovação Digital</td>
										<td class="line">19/03/2012</td>
										<td class="line">R$ 8.091</td>
										<td class="line">R$ 337</td>
										<td class="line">R$ 450</td>
										<td class="line">R$ 675</td>
									</tr>
									<tr>
										<td class="line">MBA em Marketing de Serviços</td>
										<td class="line">10/04/2012</td>
										<td class="line">R$ 8.091</td>
										<td class="line">R$ 337</td>
										<td class="line">R$ 450</td>
										<td class="line">R$ 675</td>
									</tr>
									<tr>
										<td class="line">MBA em Gestão Estratégica de Pessoas</td>
										<td class="line">17/04/2012</td>
										<td class="line">R$ 8.091</td>
										<td class="line">R$ 337</td>
										<td class="line">R$ 450</td>
										<td class="line">R$ 675</td>
									</tr>
									<tr>
										<td class="line">Pós em Gestão Educacional</td>
										<td class="line">05/05/2012</td>
										<td class="line">R$ 8.091</td>
										<td class="line">R$ 337</td>
										<td class="line">R$ 450</td>
										<td class="line">R$ 675</td>
									</tr>
									<tr>
										<td class="line">Pós em Psicopedagogia Clínica</td>
										<td class="line">12/05/2012</td>
										<td class="line">R$ 8.091</td>
										<td class="line">R$ 337</td>
										<td class="line">R$ 450</td>
										<td class="line">R$ 675</td>
									</tr>
								</table>
							</div>
						</div>
						<div>
							<h3><a href="#">6. Qual a data de início e o horário das aulas?</a></h3>
							<div>
								As aulas da graduação terão início no dia <b>27/02/2012, de 19h às 22h40.</b>.<br/>As aulas da pós-graduação iniciam conforme quadro no item 5.<br />
							</div>
						</div>
						<div>
							<h3><a href="#">7. Como é o Processo Seletivo?</a></h3>
							<div>
								As provas serão realizadas todas as segundas, terças e quartas, e as entrevistas serão nas quintas-feiras.<br/><br/>
								As provas são realizadas diretamente no computador, utilizando o banco de conteúdos da Faculdade Ipanema. Serão 25 questões, e o tempo de duração da prova é de 2 horas.<br/><br/>
								A prova é gerada de forma aleatória diretamente deste banco de conteúdos, o que faz com que nenhuma prova seja igual à outra, embora todas tenham exatamente o mesmo grau de dificuldade. A nota é dada na mesma hora e os candidatos aprovados na prova serão encaminhados para a entrevista individual.<br/><br/>
								Uma vez aprovado na prova, o candidato será encaminhado para a entrevista individual.<br/><br/>
								As entrevistas ocorrerão todas as quintas feiras, em horários previamente agendados e com duração de 20 minutos, quando o candidato deverá discorrer, diante de uma banca composta por até 3 pessoas, sobre temas da atualidade. O tema de cada candidato será informado no momento do agendamento da entrevista.
							</div>
						</div>
						<div>
							<h3><a href="#">8. Como faço para me inscrever?</a></h3>
							<div>
								Para agendar a prova o candidato deve ligar para <b>2101-0130</b> ou <b>2101-0111</b>.<br/>
								Também pode ser agendada pelo site <b>www.faculdadeipanema.com.br</b>.<br/>
								As inscrições são <b>GRATUITAS</b>!
							</div>
						</div>
						<div>
							<h3><a href="#">9. Telefone e email de contato? Site? A quem procurar?</a></h3>
							<div>
								<b>Secretaria:</b> Francine Moraes &#8212; <b>2101-0138</b> &#8212; <a href="mailto:francine.moraes@faculdadeipanema.com.br">francine.moraes@faculdadeipanema.com.br</a><br/>
								<b>Comercial:</b> Eliene Silva &#8212; <b>2101-0130</b> &#8212; <a href="mailto:eliene.silva@faculdadeipanema.com.br">eliene.silva@faculdadeipanema.com.br</a><br/>
								<b>Diretoria Acadêmica:</b> Nadir Neves &#8212; <b>2101-0136</b> &#8212; <a href="mailto:nadir.neves@faculdadeipanema.com.br">nadir.neves@faculdadeipanema.com.br</a>
							</div>
						</div>
						<div>
							<h3><a href="#">10. Quem são os professores?</a></h3>
							<div>
								Nosso corpo docente é composto pelos melhores profissionais do mercado.<br/>O processo de seleção dos professores garante, através de uma criteriosa avaliação, um perfil profissional e acadêmico capacitado para a formação de líderes.
							</div>
						</div>
						<div>
							<h3><a href="#">11. Posso me transferir de outra faculdade para a Ipanema?</a></h3>
							<div>
								Neste primeiro semestre, não receberemos alunos de transferência.<br/>
								A partir do próximo semestre esta opção já estará disponível. 
							</div>
						</div>
						<!--<div>
							<h3><a href="#">12. Onde encontro os regulamentos de campanhas e promoções?</a></h3>
							<div>
								Regulamento promoção Vestibular Premiado Jovem Pan: <a href="http://www.faculdadeipanema.com.br/FaculdadeIpanema_Regulamento_PS2012.pdf">DOWNLOAD</a><br/>
								Lista de aprovados no Vestibular Premiado Jovem Pan: <a href="http://www.faculdadeipanema.com.br/FaculdadeIpanema_Aprovados_PS2012_12_02_2012.pdf">DOWNLOAD</a><br/>
								Regulamento da campanha <i>Quem indica, amigo é!</i>: <a href="http://www.faculdadeipanema.com.br/FaculdadeIpanema_Regulamento_Campanha_Indique_2012_1.pdf">DOWNLOAD</a><br/>
							</div>
						</div>-->
		</div> 
        <h3>Continua com dúvida? Então, preencha os campos abaixo e envie sua pergunta.
Você também pode usar esse espaço para mandar comentários ou sugestões.</h3>
        <form id="form1" name="form1" method="post" action="">
          <table width="700" border="0">
    <tr>
      <td height="25" valign="bottom" class="label">Nome</td>
    </tr>
    <tr>
      <td><label for="nome"></label>
        <span id="sprytextfield1">
        <input name="name" type="text" class="input" id="nome" /></span></td>
    </tr>
    <tr>
      <td height="25" valign="bottom" class="label">Email</td>
    </tr>
    <tr>
      <td><label for="email"></label>
        <span id="sprytextfield2">
        <input name="email" type="text" class="input" id="email" />
        </span></td>
    </tr>
    <tr>
      <td height="25" valign="bottom" class="label">Telefone</td>
    </tr>
    <tr>
      <td><label for="fone"></label>
        <span id="sprytextfield3">
        <input name="phone" type="text" class="input" id="fone" />
        </span></td>
    </tr>
    <tr>
      <td height="25" valign="bottom" class="label">Mensagem</td>
    </tr>
    <tr>
      <td><label for="menssagem"></label>
        <span id="sprytextarea1">
        <textarea name="message" cols="45" rows="5" class="area" id="menssagem"></textarea>
        </span></td>
    </tr>
    <tr>
      <td><input name="enviar" type="submit" class="bt" id="enviar" value="Enviar" /></td>
    </tr>
  </table>
</form>
      </div>
      <div id="sidebar">
      <div id="content-sidebar">
    <div id="barra">Contato</div>
       <div id="title-phone">(15) 3034-9400</div>
       <span class="end">contato@faculdadeipanema.com.br<br />
       <br />
       Rua M&aacute;rio Campestrini, 100<br />
       Parque Campolim, Sorocaba / SP<br />
       <br />
       </span></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/duvidas'); ?>"><img src="<?php $this->asset('duvidas2.png','imagens'); ?>" border="0" title="Dúvidas" /></a></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/curso/empreendedor'); ?>"><img src="<?php $this->asset('empreendedor2.png','imagens'); ?>" border="0" title="Empreendedor Pearson" /></a></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/fies'); ?>"><img src="<?php $this->asset('fies2.png','imagens'); ?>" border="0" title="FIES" /></a></div>
    </div>
  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>