<?php echo $this->render('header.phtml'); ?>

<div id="container">
  <div id="content3">
      <div id="block-content3">
       <h2>D&uacute;vidas</h2>
       <h3>
         Você não tem dúvidas de que inovação é a melhor escolha para o seu futuro, né? Mas para esclarecer dúvidas sobre a Faculdade Ipanema ou sobre o vestibular, listamos aqui alguns tópicos que podem ajudar.
       </h3>
       <div id="accordion">
       		<?php
       		$id = 1; 
       		foreach($this->doubts as $doubts) : 
       		?>
       		<div>
       			<h3><a href="#"><?php echo $id; ?>. <?php echo $doubts->question; ?></a></h3>
       			<div>
       				<?php echo nl2br($doubts->answer); ?>
       			</div>
       		</div>
       		<?php
       		$id++; 
       		endforeach; 
       		?>
		</div> 
        <h3>Continua com dúvida? Então, preencha os campos abaixo e envie sua pergunta.
Você também pode usar esse espaço para mandar comentários ou sugestões.</h3>
        <form id="form1" name="form1" method="post" action="">
          <table width="700" border="0">
    <tr>
      <td height="25" valign="bottom" class="label">Nome</td>
    </tr>
    <tr>
      <td><label for="nome"></label>
        <span id="sprytextfield1">
        <input name="name" type="text" class="input" id="nome" /></span></td>
    </tr>
    <tr>
      <td height="25" valign="bottom" class="label">Email</td>
    </tr>
    <tr>
      <td><label for="email"></label>
        <span id="sprytextfield2">
        <input name="email" type="text" class="input" id="email" />
        </span></td>
    </tr>
    <tr>
      <td height="25" valign="bottom" class="label">Telefone</td>
    </tr>
    <tr>
      <td><label for="fone"></label>
        <span id="sprytextfield3">
        <input name="phone" type="text" class="input" id="fone" />
        </span></td>
    </tr>
    <tr>
      <td height="25" valign="bottom" class="label">Mensagem</td>
    </tr>
    <tr>
      <td><label for="menssagem"></label>
        <span id="sprytextarea1">
        <textarea name="message" cols="45" rows="5" class="area" id="menssagem"></textarea>
        </span></td>
    </tr>
    <tr>
      <td><input name="enviar" type="submit" class="bt" id="enviar" value="Enviar" /></td>
    </tr>
  </table>
</form>
      </div>
      <div id="sidebar">
      <div id="content-sidebar">
    <div id="barra">Contato</div>
       <div id="title-phone">(15) 3034-9400</div>
       <span class="end">contato@faculdadeipanema.com.br<br />
       <br />
       Rua M&aacute;rio Campestrini, 100<br />
       Parque Campolim, Sorocaba / SP<br />
       <br />
       </span></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/duvidas'); ?>"><img src="<?php $this->asset('duvidas2.png','imagens'); ?>" border="0" title="Dúvidas" /></a></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/curso/empreendedor'); ?>"><img src="<?php $this->asset('empreendedor2.png','imagens'); ?>" border="0" title="Empreendedor Pearson" /></a></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/fies'); ?>"><img src="<?php $this->asset('fies2.png','imagens'); ?>" border="0" title="FIES" /></a></div>
    </div>
  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>