<?php echo $this->render('header.phtml'); ?>

<div id="container">
  <div id="content3">
      <div id="block-content3">
       <h2>Como Ingressar</h2>
       <h3>
       <span class="subtitlte"><br />
       VESTIBULAR </span><br />
         <br />
         Parabéns! Você já escolheu a melhor e mais inovadora faculdade de Sorocaba. Está no caminho certo para se tornar um dos profissionais mais desejados pelo mercado. Agora, inscreva-se pelo site em uma de nossas datas de vestibulares e teste seus conhecimentos. Uma vez aprovado, você será convidado à comparecer em nossa unidade munido dos seguintes documentos:
         <br />
         <br />
         •	Histórico escolar da instituição de origem;
         <br />
         •	Conteúdo programático das disciplinas cursadas ou em curso;
         <br />
         •	Critério de avaliação da instituição de origem (média para aprovação);
         <br />
         •	Declaração de autorização ou reconhecimento do curso pelo MEC;
         <br />
         •	Declaração da instituição de origem que comprove vínculo;
         <br />
         •	Carteira de Identidade e CPF;
         <br />
         •	Histórico escolar do ensino médio (duas cópias simples acompanhadas do original);
         <br />
         •	Comprovante de residência;
<br />
<br />
<br />
<span class="subtitlte">TRANSFERÊNCIA</span><br />
<br />
Se você optou por fazer diferente em sua vida e se tornar de fato um líder completo, a Faculdade Ipanema aceitará você de braços abertos. Este é o momento!! Para isto, algumas regras devem ser levadas em consideração:
<br />
<br />
•	Somente serão aceitas as transferências até o nosso limite de vagas disponíveis;
<br />
•	Será feita análise curricular para aproveitamento, ou não, de disciplinas cursadas;
Após estas análises legais e regimentais, o candidato deverá apresentar a seguinte documentação através de cópia simples para matrícula:
<br />
•	Histórico escolar da instituição de origem;
<br />
•	Conteúdo programático das disciplinas cursadas ou em curso;
<br />
•	Critério de avaliação da instituição de origem (média para aprovação);
<br />
•	Declaração de autorização ou reconhecimento do curso pelo MEC;
<br />
•	Declaração da instituição de origem que comprove vínculo;
<br />
•	Carteira de Identidade e CPF;
<br />
•	Histórico escolar do ensino médio (duas cópias simples acompanhadas do original);
<br />
•	Comprovante de residência;
<br />
<br />
<span class="subtitlte">NOVA GRADUAÇÃO</span><br />
<br />
Você que ainda não está contente com sua formação e busca um curso complementar, a Faculdade Ipanema aceitará requerimentos de portadores de diploma de curso superior, para obtenção de nova titulação de graduação. Neste caso, solicitamos a apresentação da seguinte documentação:
<br />
<br />
•	Diploma de curso superior - uma cópia simples acompanhada do original;
<br />
•	Histórico escolar - uma cópia simples acompanhada do original;
<br />
•	Conteúdo programático das disciplinas cursadas;
<br />
•	Carteira de Identidade e CPF - uma cópia simples acompanhada do original;
<br />
•	Histórico escolar do ensino médio - duas cópias acompanhadas do original;
<br />
•	Comprovante de residência - uma cópia simples.
<br />
<br />
Após detalhada análise da documentação apresentada, o candidato será chamado para a efetivação de sua matrícula. Para tal, faz-se necessário a apresentação dos seguintes documentos:
<br />
<br />
•	Certificado de conclusão do ensino médio ou equivalente - duas cópias simples acompanhadas do original;
<br />
•	Histórico escolar do ensino médio - duas cópias simples acompanhadas do original;
<br />
•	Comprovante das obrigações eleitorais: Título de Eleitor e comprovante de votação nos dois turnos da última eleição - uma cópia simples;
<br />
•	Comprovante das obrigações do serviço militar - uma cópia simples;
<br />
•	Carteira de identidade e CPF - uma cópia simples;
<br />
•	Duas fotos 3x4 recentes;
<br />
•	Comprovante de residência (conta de luz, água ou telefone) - uma cópia simples;
<br />
•	Certidão de nascimento ou casamento - uma cópia simples acompanhada do original.

       </h3>
      </div>
    <div id="sidebar">
      <div id="content-sidebar">
       <div id="title-sidebar">A Ipanema</div>
           <ul class="menusid">
            <li><a href="<?php echo $this->baseUrl('/conheca'); ?>" title="Conheça a Ipanema">Conheça a Ipanema</a></li>
            <li><a href="<?php echo $this->baseUrl('/estrutura'); ?>" title="Estrutura">Estrutura</a></li>
            <li><a href="<?php echo $this->baseUrl('/comoingressar'); ?>" title="Como Ingressar">Como Ingressar</a></li>
            <li><a href="<?php echo $this->baseUrl('/noticias'); ?>" title="Notícias">Notícias</a></li>
           </ul>
      </div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/duvidas'); ?>"><img src="<?php $this->asset('duvidas2.png','imagens'); ?>" border="0" title="Dúvidas" /></a></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/curso/empreendedor'); ?>"><img src="<?php $this->asset('empreendedor2.png','imagens'); ?>" border="0" title="Empreendedor Pearson" /></a></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/fies'); ?>"><img src="<?php $this->asset('fies2.png','imagens'); ?>" border="0" title="FIES" /></a></div>
    </div>
  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>