<?php echo $this->render('header.phtml'); ?>

<div id="container2">
  <div id="title">Cadastrar novo &aacute;lbum</div>
  <div id="formulario">
      <form id="form1" name="form1" method="post" action="" enctype="multipart/form-data">
    <table width="1019" border="0">
      <tr>
        <td height="30" valign="bottom" class="label">T&iacute;tulo do &aacute;lbum</td>
      </tr>
      <tr>
        <td height="30" valign="bottom"><label for="titulo"></label>
          <input name="title" type="text" class="input" id="titulo" /></td>
      </tr>
      <tr>
        <td height="30" valign="bottom" class="label">Descri&ccedil;&atilde;o do &aacute;lbum</td>
      </tr>
      <tr>
        <td height="30" valign="bottom"><label for="descricao"></label>
          <textarea name="description" cols="45" rows="5" class="area2" id="descricao"></textarea> 
          <em><span class="info"><strong>M&aacute;x 400 caracteres</strong></span></em></td>
      </tr>
      <tr>
        <td height="30" valign="bottom"><span class="label">Adicionar imagens</span></td>
      </tr>
      <tr>
        <td><input name="image[]" class="multi" maxlength="12" type="file" id="image1" />
        <label><em><span class="info">(600 x 400px Arquivo - JPG) <strong>M&aacute;ximo 12 imagens</strong></span></em></label></td>
      </tr>
      <tr>
        <td height="45"><input name="cadastrar" type="submit" class="bt" id="cadastrar" value="Cadastrar" /></td>
      </tr>
    </table>
    <br />
    </form>


  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>