<?php echo $this->render('header.phtml'); ?>

<div id="container">
  <div id="content">
      <div id="block-content1">
       <h2>Not&iacute;cias</h2>
   		<ul class="tabela3">
   			<?php foreach($this->paginator as $news) : ?>
   			<li>
   				<a href="<?php echo $this->baseUrl('/noticia/' . $news->idnews . ',,' . urlencode($news->title)); ?>" class="linkn"><?php echo $news->title; ?></a>
   				<span class="data-not"><?php echo $this->date($news->date); ?></span>
   				<a href="<?php echo $this->baseUrl('/noticia/' . $news->idnews . ',,' . urlencode($news->title)); ?>" class="linkb"><?php echo substr($this->stripTags($news->content),0,200) . '...'; ?></a>
   			</li>
   			<?php endforeach; ?>
      </ul>
      <div id="paginacao">
            <div id="tnt_pagination">
			
				<?php echo $this->paginationcontrol($this->paginator,null,'news/pagination.phtml'); ?>
			
			</div>
       </div>
      </div>
    <div id="sidebar">
      <div id="content-sidebar">
       <div id="title-sidebar">A Ipanema</div>
           <ul class="menusid">
            <li><a href="<?php echo $this->baseUrl('/conheca'); ?>" title="Conheça a Ipanema">Conheça a Ipanema</a></li>
            <li><a href="<?php echo $this->baseUrl('/estrutura'); ?>" title="Estrutura">Estrutura</a></li>
            <li><a href="<?php echo $this->baseUrl('/comoingressar'); ?>" title="Como Ingressar">Como Ingressar</a></li>
            <li><a href="<?php echo $this->baseUrl('/noticias'); ?>" title="Notícias">Notícias</a></li>
           </ul>
      </div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/duvidas'); ?>"><img src="<?php $this->asset('duvidas2.png','imagens'); ?>" border="0" title="Dúvidas" /></a></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/curso/empreendedor'); ?>"><img src="<?php $this->asset('empreendedor2.png','imagens'); ?>" border="0" title="Empreendedor Pearson" /></a></div>
      <div id="mini-banner"><a href="<?php echo $this->baseUrl('/fies'); ?>"><img src="<?php $this->asset('fies2.png','imagens'); ?>" border="0" title="FIES" /></a></div>
    </div>
  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>